INSERT INTO customers (name, email, region_id, signup_date, is_returning) VALUES
    -- North (15 customers)
    ('Aarav Sharma', 'aarav.sharma1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2023-11-02', TRUE),
    ('Priya Nair', 'priya.nair1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2023-12-10', TRUE),
    ('Karan Mehta', 'karan.mehta1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-01-05', TRUE),
    ('Sara Iqbal', 'sara.iqbal1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-01-20', FALSE),
    ('Rohan Gupta', 'rohan.gupta1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-02-01', TRUE),
    ('Ananya Rao', 'ananya.rao1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-02-14', FALSE),
    ('Vikram Joshi', 'vikram.joshi1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-02-28', TRUE),
    ('Neha Kapoor', 'neha.kapoor1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-03-15', TRUE),
    ('Arjun Verma', 'arjun.verma1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-03-22', FALSE),
    ('Ishita Sen', 'ishita.sen1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-04-02', TRUE),
    ('Devansh Rathi', 'devansh.rathi1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-04-10', TRUE),
    ('Meera Pillai', 'meera.pillai1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-04-18', FALSE),
    ('Yash Malhotra', 'yash.malhotra1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-05-01', TRUE),
    ('Divya Chawla', 'divya.chawla1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-05-15', TRUE),
    ('Nikhil Bose', 'nikhil.bose1@example.com', (SELECT id FROM regions WHERE name = 'North'), '2024-05-30', FALSE),

    -- South (15 customers)
    ('Lakshmi Iyer', 'lakshmi.iyer1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2023-11-05', TRUE),
    ('Suresh Reddy', 'suresh.reddy1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2023-12-01', TRUE),
    ('Kavya Menon', 'kavya.menon1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-01-08', FALSE),
    ('Arun Kumar', 'arun.kumar1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-01-25', TRUE),
    ('Deepika Rao', 'deepika.rao1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-02-05', TRUE),
    ('Manoj Pillai', 'manoj.pillai1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-02-18', FALSE),
    ('Swathi Nair', 'swathi.nair1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-03-01', TRUE),
    ('Ravi Shankar', 'ravi.shankar1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-03-12', TRUE),
    ('Anitha Krishnan', 'anitha.krishnan1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-03-28', FALSE),
    ('Vijay Subramaniam', 'vijay.subramaniam1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-04-05', TRUE),
    ('Divya Raman', 'divya.raman1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-04-15', TRUE),
    ('Harish Babu', 'harish.babu1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-04-25', FALSE),
    ('Nandini Rajan', 'nandini.rajan1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-05-05', TRUE),
    ('Prakash Iyer', 'prakash.iyer1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-05-20', TRUE),
    ('Meenakshi Devi', 'meenakshi.devi1@example.com', (SELECT id FROM regions WHERE name = 'South'), '2024-05-28', FALSE),

    -- East (15 customers)
    ('Sourav Das', 'sourav.das1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2023-11-10', TRUE),
    ('Riya Chatterjee', 'riya.chatterjee1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2023-12-15', TRUE),
    ('Abhishek Ghosh', 'abhishek.ghosh1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-01-10', FALSE),
    ('Payal Bhattacharya', 'payal.bhattacharya1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-01-28', TRUE),
    ('Debashish Roy', 'debashish.roy1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-02-08', TRUE),
    ('Ipsita Mishra', 'ipsita.mishra1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-02-20', FALSE),
    ('Bikash Sarkar', 'bikash.sarkar1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-03-05', TRUE),
    ('Sneha Das', 'sneha.das1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-03-18', TRUE),
    ('Tapan Nayak', 'tapan.nayak1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-04-01', FALSE),
    ('Ruma Sengupta', 'ruma.sengupta1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-04-12', TRUE),
    ('Anupam Dutta', 'anupam.dutta1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-04-22', TRUE),
    ('Moumita Halder', 'moumita.halder1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-05-02', FALSE),
    ('Subrata Paul', 'subrata.paul1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-05-12', TRUE),
    ('Ananya Basu', 'ananya.basu1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-05-25', TRUE),
    ('Rajib Saha', 'rajib.saha1@example.com', (SELECT id FROM regions WHERE name = 'East'), '2024-05-30', FALSE),

    -- West (15 customers)
    ('Aditi Deshmukh', 'aditi.deshmukh1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2023-11-15', TRUE),
    ('Rahul Patil', 'rahul.patil1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2023-12-20', TRUE),
    ('Snehal Joshi', 'snehal.joshi1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-01-12', FALSE),
    ('Nikhil Shah', 'nikhil.shah1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-01-30', TRUE),
    ('Pooja Kulkarni', 'pooja.kulkarni1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-02-10', TRUE),
    ('Sameer Bhosale', 'sameer.bhosale1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-02-22', FALSE),
    ('Trupti More', 'trupti.more1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-03-08', TRUE),
    ('Ganesh Pawar', 'ganesh.pawar1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-03-20', TRUE),
    ('Vaishnavi Naik', 'vaishnavi.naik1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-04-03', FALSE),
    ('Om Kadam', 'om.kadam1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-04-14', TRUE),
    ('Ketaki Sawant', 'ketaki.sawant1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-04-24', TRUE),
    ('Rajesh Chavan', 'rajesh.chavan1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-05-04', FALSE),
    ('Shalini Gaikwad', 'shalini.gaikwad1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-05-14', TRUE),
    ('Amol Jadhav', 'amol.jadhav1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-05-24', TRUE),
    ('Pallavi Kale', 'pallavi.kale1@example.com', (SELECT id FROM regions WHERE name = 'West'), '2024-05-29', FALSE);